### ISSUE TITLE
Not possibe to set the Cacheable() method's settings globally

### ISSUE THREAD

**Issue by aboondeviant** [VahidN/EFCoreSecondLevelCacheInterceptor#22] opened 2020-04-16 09:02 UTC
# Summary of the issue
The documentation says it's possible to set the Cacheable() method's settings globally.

```c#
services.AddEFSecondLevelCache(options => options.UseMemoryCacheProvider(CacheExpirationMode.Absolute, TimeSpan.FromMinutes(5)).DisableLogging(true));
```
```c#
var post1 = context.Posts
                   .Where(x => x.Id > 0)
                   .OrderBy(x => x.Id)
                   .Cacheable()
                   .FirstOrDefault();  // Async methods are supported too.
```

But the Cacheable() function is hardcoded to always use 30 minutes:
https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/blob/master/src/EFCoreSecondLevelCacheInterceptor/EFCachedQueryExtensions.cs#L164

What is the intended purpose of the ``UseMemoryCacheProvider(CacheExpirationMode expirationMode, TimeSpan timeout)`` overload?

**Comment by VahidN** [comment] 2020-04-16 10:33
It's duplicate of #https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/20

**Closed by VahidN** 2020-04-16 10:33 UTC

**Comment by aboondeviant** [comment] 2020-04-16 11:56
I see, sorry.

The confusion seems to stem from the query still getting tagged with the default 30 minute policy when using ``Cacheable()`` combined with a global policy.
But it's actually using the global policy, which is not explicitly being reported to the logs.

Working great though, thank you.

**Comment by warmfire540** [comment] 2023-12-14 21:25
Is it possible to update the message in the query log to show the actual cache policy used?  This was a confusing issue and took me some time to dig and find that it was actually working :)
