### ISSUE TITLE
Error while querying for spatial column in the table - Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91

### ISSUE THREAD

**Issue by deepak-kumar2020** [VahidN/EFCoreSecondLevelCacheInterceptor#176] opened 2022-09-13 09:45 UTC
# I have a table dbo.[AspNetUsers] which has a spatial column type Geography named 'LocationPoint'. I am getting an error as 
"System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.'

## Local environment

```
.NET (Core) SDK version:  6.0
Microsoft.EntityFrameworkCore version:  6.0
EFCoreSecondLevelCacheInterceptor version:  3.6.3
Database: (e.g. SQL Server, SQLite, etc.): Sql Server 2019
Cache provider: (e.g. in-memory, redis, etc.) redis
```

## Example code/Steps to reproduce:
1.) Run the EF query with a spatial column in any of the table(event for one table). In the below query LocationPoint is of Geography type in Sql server.

```
context.Users.Where(u => u.Id == userId).Select(a => new { a.LocationPoint }).Cacheable().FirstOrDefault()

Exception message: System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'. The system cannot find the file specified.'

**Comment by nbbdev** [comment] 2022-09-29 12:40
I have this problem when I use `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`

**Comment by VahidN** [comment] 2022-10-01 11:00
It's duplicate of https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor/issues/4

**Closed by VahidN** 2022-10-01 11:00 UTC
