### ISSUE TITLE
Dynamically built Linq queries with differing parameters have their results cached incorrectly

### ISSUE THREAD

**Issue by JerrettDavis** [VahidN/EFCoreSecondLevelCacheInterceptor#111] opened 2021-03-10 16:40 UTC
# Summary of the issue

I have several pieces of functionality that rely on dynamically built Linq queries. These queries apply various filters by way of optionally chained `Where` methods. When these queries (with differing parameters) have `CountAsync` executed, I find that all the results are duplicated. If I disable global caching, or add `NotCacheable` to the method chain, it works as desired.

## Environment

```
.NET (Core) SDK version: 5.0
Microsoft.EntityFrameworkCore version: 5.0.4
EFCoreSecondLevelCacheInterceptor version: 2.4.1
Database: Postgresql
Cache provider: EasyCaching.InMemory - 1.2.0
```

## Example code/Steps to reproduce:

Please note, I've removed many of the available properties and filters from `JobSearchInputModel` for brevity.

```csharp
public class JobSearchInputModel
{
    public IEnumerable<int> JobStates { get; set; } = new HashSet<int>();
    public IEnumerable<int> Countries { get; set; } = new HashSet<int>();
    
    public IQueryable<SubJob> GetBaseQuery(IJobSchedulingContext context)
    {
        return context.SubJobs
            .Include(j => j.JobHeader)
            .ThenInclude(jh => jh.Region)
            .ThenInclude(r => r!.Country)
            .Include(j => j.JobState)
            .FilterCountries(Countries)
            .FilterJobStates(JobStates);
            //.NotCacheable();
    }
}

public static class JobQueryableExtensions
{
    public static IQueryable<SubJob> FilterCountries(
        this IQueryable<SubJob> jobs,
        IEnumerable<int> countries)
    {
        var countryList = countries.ToList();
        if (!countryList.Any())
            return jobs;

        jobs = jobs.Where(j => j.JobHeader.Region != null &&
                                countryList.Contains(j.JobHeader.Region.Country.Id));

        return jobs;
    }

    public static IQueryable<SubJob> FilterJobStates(
        this IQueryable<SubJob> jobs,
        IEnumerable<int> jobStates)
    {
        var jobStateList = jobStates.ToList();
        if (!jobStateList.Any())
            return jobs;

        jobs = jobs.Where(j => jobStateList.Contains(j.JobStateId));

        return jobs;
    }
}

public class GetCategoriesQueryHandler : 
    IRequestHandler<GetCategoriesQuery, IEnumerable<Category>>
{
    private readonly IJobSchedulingContext _context;

    public GetCategoriesQueryHandler(IJobSchedulingContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<Category>> Handle(
        GetCategoriesQuery request,
        CancellationToken cancellationToken)
    {
        var baseQuery = _context.Categories
            .Include(c => c.Children)
            .ThenInclude(c => c.CategoryParameters)
            .Include(c => c.CategoryParameters)
            .Where(c => c.ParentId == null);

        return (await baseQuery
                .AsNoTracking()
                .ToListAsync(cancellationToken))
            .Select(async c => 
                await ShapeCategory(
                    c, 
                    request.Countries, 
                    _context, 
                    cancellationToken))
            .Select(c => c.Result);
    }
    
    private static async Task<int> GetCount(
        JobSearchInputModel model, 
        IJobSchedulingContext context,
        CancellationToken cancellationToken)
    {
        return await model.GetBaseQuery(context)
            .CountAsync(cancellationToken);
    }

    private static JobSearchInputModel PopulateModel(
        IEnumerable<CategoryParameter> parameters)
    {
        // Instantiate our new model
        var model = new JobSearchInputModel();
        // Group params by their name, makes lists easier.
        var shapedParams = parameters.GroupBy(p => p.Name);
        foreach (var param in shapedParams)
        {
            var property = model.GetType().GetProperty(param.Key);
            if (property == null) continue;
            try
            {
                // Check if the property we're assigning is an IEnumerable
                if (typeof(IEnumerable).IsAssignableFrom(property.PropertyType))
                    property.SetValue(model, CreateList(property, param));
                else
                    // Not an enumerable, lets just attempt to set the value (after converting it).
                    property.SetValue(model, param.First().Value.ChangeType( 
                            property.PropertyType), 
                        null);
            }
            catch
            {
                // ignored
            }
        }

        return model;
    }

    private static IList CreateList(
        PropertyInfo property, 
        IEnumerable<CategoryParameter> parameter)
    {
        var list = (IList) Activator.CreateInstance(
            typeof(List<>)
                .MakeGenericType(
                    property.PropertyType.GetGenericArguments()))!;
        // Convert the values to the target type and populate the list.
        foreach (var item in parameter)
            list.Add(item.Value.ChangeType(
                property.PropertyType.GetGenericArguments()[0]));

        return list;
    }

    private static async Task<Category> ShapeCategory(
        Domain.Models.Category category,
        IEnumerable<int> countries,
        IJobSchedulingContext context,
        CancellationToken cancellationToken)
    {
        var countryList = countries.ToList();
        var model = PopulateModel(category.CategoryParameters);
        model.Countries = countryList;
        var count = await GetCount(model, context, cancellationToken);
        var children = category.Children
            .Select(async c => 
                await ShapeCategory(c, countryList, context, cancellationToken))
            .Select(c => c.Result);

        return new Category(
            category.Name,
            count,
            GetParameters(category.CategoryParameters),
            children);
    }

    private static IEnumerable<KeyValuePair<string, string>> GetParameters(
        IEnumerable<CategoryParameter> parameters) =>
        parameters.Select(p => 
            new KeyValuePair<string, string>(p.Name, p.Value));
}
```

## Output:

Expected Results:
![image](https://user-images.githubusercontent.com/2610199/110664197-d2626380-818c-11eb-905f-08af93d405d5.png)

Actual Results:
![image](https://user-images.githubusercontent.com/2610199/110664291-e0b07f80-818c-11eb-994c-4c4becee0847.png)

**Comment by VahidN** [comment] 2021-05-16 10:01
Because there is no provided sample solution to reproduce it quickly, I will close this issue.

**Closed by VahidN** 2021-05-16 10:01 UTC
